# Generated by Buildr 1.4.6, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "com.twitter.twadoop"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

COMPILE_DEPS = 'com.google.collections:google-collections:jar:1.0', 
	'org.slf4j:slf4j-log4j12:jar:1.6.1',
	'org.apache.hadoop:hadoop-core:jar:0.20.205.0',
	'org.slf4j:slf4j-api:jar:1.6.1'

desc "The Filesetinputformat project"
define "FileSetInputFormat" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  compile.with COMPILE_DEPS
  test.with COMPILE_DEPS
  package(:jar, :id => 'filesetinputformat')
end
